package View;

import Control.AccesorioControlador;
import javax.swing.*;

public class AccesorioGUI extends javax.swing.JFrame {

    private final AccesorioControlador control = new AccesorioControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public AccesorioGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        labelId = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelPrecio = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar accesorio", "Consultar accesorio", "Actualizar accesorio", "Listar accesorios", "Eliminar accesorio" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        labelId.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelId.setText("Id");
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labelDescripcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelDescripcion.setText("Descripción");
        getContentPane().add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        labelTipo.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelTipo.setText("Tipo");
        getContentPane().add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        id.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 118, -1));

        descripcion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 118, -1));

        tipo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de accesorios");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 300, 80, -1));

        labelPrecio.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelPrecio.setText("Precio");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        precio.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 118, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar accesorio":
                control.almacenarAccesorio(id.getText().trim().toUpperCase(), tipo.getText().trim(),
                        descripcion.getText().trim(), precio.getText().trim());
                break;
            case "Consultar accesorio": 
                control.consultarAccesorio(id.getText().trim());
                break;
            case "Actualizar accesorio":
                control.actualizarAccesorio(id.getText().trim().toUpperCase(), tipo.getText().trim(),
                        descripcion.getText().trim(), precio.getText().trim());
                break;
            case "Listar accesorios":
                control.listarAccesorios();
                break;
            case "Eliminar accesorio":
                control.eliminarAccesorio(id.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar accesorio":
                activarTodo();                
                break;
            case "Consultar accesorio":
                activarSoloDocumento();
                break;
            case "Actualizar accesorio":
                activarTodo();
                break;
            case "Listar accesorios":
                activarSoloDocumento();
                labelId.setEnabled(false);
                id.setEnabled(false);
                break;
            case "Eliminar accesorio":
                activarSoloDocumento();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void activarTodo(){
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelTipo.setEnabled(true);
        tipo.setEnabled(true);
        labelDescripcion.setEnabled(true);
        descripcion.setEnabled(true);
        labelPrecio.setEnabled(true);
        precio.setEnabled(true);
    }
    
    public void activarSoloDocumento(){
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelTipo.setEnabled(false);
        tipo.setEnabled(false);
        labelDescripcion.setEnabled(false);
        descripcion.setEnabled(false);
        labelPrecio.setEnabled(false);
        precio.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesorioGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
