package View;

import Control.ClienteControlador;
import javax.swing.*;

public class ClienteGUI extends javax.swing.JFrame {

    private final ClienteControlador control = new ClienteControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public ClienteGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        identificacion = new javax.swing.JTextField();
        labelIdentificacion = new javax.swing.JLabel();
        labelNombres = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar cliente", "Consultar cliente", "Actualizar cliente", "Listar clientes", "Eliminar cliente" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        identificacion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 118, -1));

        labelIdentificacion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdentificacion.setText("Identificación");
        getContentPane().add(labelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labelNombres.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelNombres.setText("Nombres");
        getContentPane().add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelDireccion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelDireccion.setText("Dirección");
        getContentPane().add(labelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        labelNumero.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelNumero.setText("Número");
        getContentPane().add(labelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        nombres.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 118, -1));

        direccion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 118, -1));

        numero.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de clientes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 300, 80, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 10, 10));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar cliente":
                control.almacenarCliente(identificacion.getText().trim().toUpperCase(), nombres.getText().trim().toUpperCase(),
                        direccion.getText().trim().toUpperCase(), numero.getText().trim());
                break;
            case "Consultar cliente": 
                control.consultarCliente(identificacion.getText().trim());
                break;
            case "Actualizar cliente":
                control.actualizarCliente(identificacion.getText().trim().toUpperCase(), nombres.getText().trim().toUpperCase(),
                        direccion.getText().trim().toUpperCase(), numero.getText().trim());
                break;
            case "Listar clientes":
                control.listarClientes();
                break;
            case "Eliminar cliente":
                control.eliminarCliente(identificacion.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar cliente":
                activarTodo();                
                break;
            case "Consultar cliente":
                activarSoloDocumento();
                break;
            case "Actualizar cliente":
                activarTodo();
                break;
            case "Listar clientes":
                activarSoloDocumento();
                labelIdentificacion.setEnabled(false);
                identificacion.setEnabled(false);
                break;
            case "Eliminar cliente":
                activarSoloDocumento();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void activarTodo(){
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelNombres.setEnabled(true);
        nombres.setEnabled(true);
        labelDireccion.setEnabled(true);
        direccion.setEnabled(true);
        labelNumero.setEnabled(true);
        numero.setEnabled(true);
    }
    
    public void activarSoloDocumento(){
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelNombres.setEnabled(false);
        nombres.setEnabled(false);
        labelDireccion.setEnabled(false);
        direccion.setEnabled(false);
        labelNumero.setEnabled(false);
        numero.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField identificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
