package View;

import Control.MascotaControlador;
import javax.swing.*;

public class MascotaGUI extends javax.swing.JFrame {

    private final MascotaControlador control = new MascotaControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public MascotaGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelRaza = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        raza = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        lugarOrigen = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelLugarOrigen = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar mascota", "Consultar mascota", "Actualizar mascota", "Registrar consulta", "Registrar vacuna", "Listar mascotas", "Eliminar mascota" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        nombre.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 118, -1));

        labelNombre.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelNombre.setText("Nombre(s)");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labelRaza.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelRaza.setText("Raza");
        getContentPane().add(labelRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelEdad.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelEdad.setText("Edad");
        getContentPane().add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        labelTipo.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelTipo.setText("Tipo");
        getContentPane().add(labelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        raza.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 118, -1));

        edad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 118, -1));

        tipo.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de mascotas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        lugarOrigen.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(lugarOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 118, -1));

        genero.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 118, -1));

        id.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 118, -1));

        labelId.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelId.setText("Id");
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        labelPeso.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelPeso.setText("Peso (kg)");
        getContentPane().add(labelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        labelLugarOrigen.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelLugarOrigen.setText("Origen");
        getContentPane().add(labelLugarOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        labelGenero.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelGenero.setText("Género");
        getContentPane().add(labelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        peso.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 118, -1));

        precio.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 118, -1));

        labelPrecio.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelPrecio.setText("Precio");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        estado.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 118, -1));

        labelEstado.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelEstado.setText("Estado ");
        getContentPane().add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 80, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar mascota":
                control.almacenarMascota(nombre.getText().trim().toUpperCase(), raza.getText().trim().toUpperCase(), edad.getText().trim(), 
                        tipo.getText().trim().toUpperCase(), id.getText().trim(), peso.getText().trim(), java.time.LocalDate.now().toString(), 
                        lugarOrigen.getText().trim().toUpperCase(), genero.getText().trim().toUpperCase(), precio.getText().trim(), estado.getText().trim().toUpperCase());
                break;    
            case "Consultar mascota":
                control.consultarMascota(id.getText().trim());
                break;
                
            case "Registrar consulta":
                ConsultaGUI consulta = new ConsultaGUI();
                consulta.setVisible(true);
                break;
            
            case "Registrar vacuna":
                VacunaMascotaGUI vacuna = new VacunaMascotaGUI();
                vacuna.setVisible(true);
                break;
                
            case "Actualizar mascota":
                control.actualizarMascota(nombre.getText().trim().toUpperCase(), raza.getText().trim().toUpperCase(), edad.getText().trim(), 
                        tipo.getText().trim().toUpperCase(), id.getText().trim(), peso.getText().trim(), java.time.LocalDate.now().toString(), 
                        lugarOrigen.getText().trim().toUpperCase(), genero.getText().trim().toUpperCase(), precio.getText().trim(), estado.getText().trim().toUpperCase());
                break;
            case "Listar mascotas":
                control.listarMascotas();
                break;
            case "Eliminar mascota":
                control.eliminarMascota(id.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar mascota":
                activarTodo();                
                break;
            case "Consultar mascota":
                activarSoloDocumento();
                break;
            case "Actualizar mascota":
                activarTodo();
                break;
            case "Registrar consulta":
                desactivarTodo();
                break;
            case "Registrar vacuna":
                desactivarTodo();
                break;
            case "Listar mascotas":
                desactivarTodo();
                break;
            case "Eliminar mascota":
                activarSoloDocumento();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed
    
    public void activarTodo(){
        labelNombre.setEnabled(true);
        nombre.setEnabled(true);
        labelRaza.setEnabled(true);
        raza.setEnabled(true);
        labelEdad.setEnabled(true);
        edad.setEnabled(true);
        labelTipo.setEnabled(true);
        tipo.setEnabled(true);
        labelEstado.setEnabled(true);
        estado.setEnabled(true);
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelPeso.setEnabled(true);
        peso.setEnabled(true);
        labelLugarOrigen.setEnabled(true);
        lugarOrigen.setEnabled(true);
        labelGenero.setEnabled(true);
        genero.setEnabled(true);
        labelPrecio.setEnabled(true);
        precio.setEnabled(true);
    }
    
    public void activarSoloDocumento(){
        labelNombre.setEnabled(false);
        nombre.setEnabled(false);
        labelRaza.setEnabled(false);
        raza.setEnabled(false);
        labelEdad.setEnabled(false);
        edad.setEnabled(false);
        labelTipo.setEnabled(false);
        tipo.setEnabled(false);
        labelEstado.setEnabled(false);
        estado.setEnabled(false);
        labelId.setEnabled(true);
        id.setEnabled(true);
        labelPeso.setEnabled(false);
        peso.setEnabled(false);
        labelLugarOrigen.setEnabled(false);
        lugarOrigen.setEnabled(false);
        labelGenero.setEnabled(false);
        genero.setEnabled(false);
        labelPrecio.setEnabled(false);
        precio.setEnabled(false);
    }
    
    public void desactivarTodo(){
        labelNombre.setEnabled(false);
        nombre.setEnabled(false);
        labelRaza.setEnabled(false);
        raza.setEnabled(false);
        labelEdad.setEnabled(false);
        edad.setEnabled(false);
        labelTipo.setEnabled(false);
        tipo.setEnabled(false);
        labelEstado.setEnabled(false);
        estado.setEnabled(false);
        labelId.setEnabled(false);
        id.setEnabled(false);
        labelPeso.setEnabled(false);
        peso.setEnabled(false);
        labelLugarOrigen.setEnabled(false);
        lugarOrigen.setEnabled(false);
        labelGenero.setEnabled(false);
        genero.setEnabled(false);
        labelPrecio.setEnabled(false);
        precio.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MascotaGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelLugarOrigen;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelRaza;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField lugarOrigen;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField raza;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
