package View;

import Control.ClienteControlador;
import Control.VentaControlador;
import Implement.VentaDAOFile;
import Model.MascotaDto;
import Model.VentaDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

public class ReportesGUI extends javax.swing.JFrame {

    private final VentaControlador ventaControl = new VentaControlador();
    private final ClienteControlador clienteControl = new ClienteControlador();

    /**
     * Creates new form EstudianteGUI
     */
    public ReportesGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        opcion = new javax.swing.JComboBox<>();
        labelIdCliente = new javax.swing.JLabel();
        idMascota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelIdMascota = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelIdVenta = new javax.swing.JLabel();
        idVenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 80, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar ventas", "Consultar venta", "Listar mascotas por cliente", "Mostrar cliente por mascota" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        labelIdCliente.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdCliente.setText("Id cliente");
        getContentPane().add(labelIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        idMascota.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(idMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Reportes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        idCliente.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteActionPerformed(evt);
            }
        });
        getContentPane().add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 118, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 80, -1));

        labelIdMascota.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdMascota.setText("Id mascota");
        getContentPane().add(labelIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel3.setText("Seleccione el tipo de venta ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 20, 20));

        labelIdVenta.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdVenta.setText("Id venta");
        getContentPane().add(labelIdVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        idVenta.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        idVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idVentaActionPerformed(evt);
            }
        });
        getContentPane().add(idVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 118, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch (opcion.getSelectedItem().toString()) {
            case "Listar ventas":
                ventaControl.listarVentas();
                break;

            case "Consultar venta":
                ventaControl.consultarVenta(idVenta.getText());
                break;

            case "Listar mascotas por cliente":
                clienteControl.consultarCliente(idCliente.getText().trim());
                break;

            case "Mostrar cliente por mascota":
                String mensaje = "";
                List<VentaDto> ventas = new VentaDAOFile().listarVentas();
                for (VentaDto venta : ventas) {
                    for (MascotaDto mascota : venta.getMascotas()) {
                        if (idMascota.getText().equals(mascota.getId())) {
                            mensaje += "Mascota: " + mascota.getNombre() + ", Id: " + mascota.getId() + ", Tipo: " + mascota.getTipo()
                                    + ", Precio: " + String.valueOf(mascota.getPrecio()) + " Dueño: " + venta.getCliente().getNombres()
                                    + ", Documento: " + venta.getCliente().getIdentificacion() + ", Teléfono: " + venta.getCliente().getNumeroContacto();
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, mensaje, "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch (opcion.getSelectedItem().toString()) {
            case "Listar ventas":
                desactivarTodo();
                break;

            case "Consultar venta":
                desactivarTodo();
                labelIdVenta.setEnabled(true);
                idVenta.setEnabled(true);
                break;

            case "Listar mascotas por cliente":
                desactivarTodo();
                labelIdCliente.setEnabled(true);
                idCliente.setEnabled(true);
                break;
                
            case "Mostrar cliente por mascota":
                desactivarTodo();
                labelIdMascota.setEnabled(true);
                idMascota.setEnabled(true);
                break;

        }
    }//GEN-LAST:event_opcionActionPerformed

    private void idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void idVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idVentaActionPerformed

    public void desactivarTodo() {
        labelIdVenta.setEnabled(false);
        idVenta.setEnabled(false);
        labelIdCliente.setEnabled(false);
        idCliente.setEnabled(false);
        labelIdMascota.setEnabled(false);
        idMascota.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField idCliente;
    private javax.swing.JTextField idMascota;
    private javax.swing.JTextField idVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelIdCliente;
    private javax.swing.JLabel labelIdMascota;
    private javax.swing.JLabel labelIdVenta;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
