package View;


import Control.ConsultaControlador;
import Control.DosisControlador;
import javax.swing.*;

public class VacunaMascotaGUI extends javax.swing.JFrame {

    private final DosisControlador control = new DosisControlador();

    /**
     * Creates new form EstudianteGUI
     */
    public VacunaMascotaGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        idMascota = new javax.swing.JTextField();
        labelNombres = new javax.swing.JLabel();
        labelIdVacuna = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        idVacuna = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        idMascota.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(idMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, -1));

        labelNombres.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelNombres.setText("Id mascota");
        getContentPane().add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelIdVacuna.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdVacuna.setText("Id vacuna");
        getContentPane().add(labelIdVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        labelCantidad.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelCantidad.setText("Cantidad");
        getContentPane().add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        idVacuna.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(idVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        cantidad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registrar vacuna");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 10, 10));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vacuna-para-mascotas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        boolean exitoso = control.registrarVacunaMascota(java.time.LocalDateTime.now().toString(), idMascota.getText(), idVacuna.getText(), cantidad.getText());
        if(exitoso){
            this.dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VacunaMascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VacunaMascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VacunaMascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VacunaMascotaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VacunaMascotaGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField idMascota;
    private javax.swing.JTextField idVacuna;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelIdVacuna;
    private javax.swing.JLabel labelNombres;
    // End of variables declaration//GEN-END:variables
}
