package View;

import Control.VendedorControlador;
import javax.swing.*;

public class VendedorGUI extends javax.swing.JFrame {

    private final VendedorControlador control = new VendedorControlador();
    /**
     * Creates new form EstudianteGUI
     */
    public VendedorGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        nombres = new javax.swing.JTextField();
        labelNombres = new javax.swing.JLabel();
        labelIdentificacion = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel1.setText("Seleccione una de las opciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar vendedor", "Consultar vendedor", "Actualizar vendedor", "Listar vendedores", "Eliminar vendedor" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        nombres.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 118, -1));

        labelNombres.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelNombres.setText("Nombres");
        getContentPane().add(labelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        labelIdentificacion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdentificacion.setText("Identificación");
        getContentPane().add(labelIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        labelGenero.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelGenero.setText("Género");
        getContentPane().add(labelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        identificacion.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 118, -1));

        genero.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de vendedores");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 10, 10));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 10, 10));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar vendedor":
                control.almacenarVendedor(nombres.getText().trim().toUpperCase(), identificacion.getText().trim(),
                        genero.getText().trim().toUpperCase());
                break;
            case "Consultar vendedor": 
                control.consultarVendedor(identificacion.getText().trim());
                break;
            case "Actualizar vendedor":
                control.actualizarVendedor(nombres.getText().trim().toUpperCase(), identificacion.getText().trim(),
                        genero.getText().trim().toUpperCase());
                break;
            case "Listar vendedores":
                control.listarVendedores();
                break;
            case "Eliminar vendedor":
                control.eliminarVendedor(identificacion.getText().trim());
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Agregar vendedor":
                activarTodo();                
                break;
            case "Consultar vendedor":
                activarSoloDocumento();
                break;
            case "Actualizar vendedor":
                activarTodo();
                break;
            case "Listar vendedores":
                activarSoloDocumento();
                labelIdentificacion.setEnabled(false);
                identificacion.setEnabled(false);
                break;
            case "Eliminar vendedor":
                activarSoloDocumento();
                break;
        }
    }//GEN-LAST:event_opcionActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void activarTodo(){
        labelNombres.setEnabled(true);
        nombres.setEnabled(true);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelGenero.setEnabled(true);
        genero.setEnabled(true);
    }
    
    public void activarSoloDocumento(){
        labelNombres.setEnabled(false);
        nombres.setEnabled(false);
        labelIdentificacion.setEnabled(true);
        identificacion.setEnabled(true);
        labelGenero.setEnabled(false);
        genero.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField identificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JTextField nombres;
    private javax.swing.JComboBox<String> opcion;
    // End of variables declaration//GEN-END:variables
}
