package View;

import Business.AccesorioNegocio;
import Business.MascotaNegocio;
import Business.VentaNegocio;
import Control.AccesorioControlador;
import Control.ClienteControlador;
import Control.MascotaControlador;
import Control.VentaControlador;
import Model.AccesorioDto;
import Model.MascotaDto;
import Model.VentaDto;
import java.util.List;
import java.util.UUID;
import javax.swing.*;

public class VentaGUI extends javax.swing.JFrame {
    
    private final VentaControlador ventaControl = new VentaControlador();
    private ClienteControlador clienteControl = new ClienteControlador();
    private MascotaNegocio mascotaNegocio = new MascotaNegocio();
    private AccesorioNegocio accesorioNegocio = new  AccesorioNegocio();
    /**
     * Creates new form EstudianteGUI
     */
    public VentaGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcion = new javax.swing.JComboBox<>();
        idAccesorio = new javax.swing.JTextField();
        labelIdCliente = new javax.swing.JLabel();
        labelIdVendedor = new javax.swing.JLabel();
        labelAccesorio = new javax.swing.JLabel();
        idVendedor = new javax.swing.JTextField();
        idMascota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelIdMascota = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        botonInstrucciones = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 80, -1));

        jLabel1.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel1.setText("De click si desea ver el listado de accesorios o mascotas disponibles ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        opcion.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mascota y accesorio", "Solo mascota" }));
        opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActionPerformed(evt);
            }
        });
        getContentPane().add(opcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        idAccesorio.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        idAccesorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAccesorioActionPerformed(evt);
            }
        });
        getContentPane().add(idAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 118, -1));

        labelIdCliente.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdCliente.setText("Id cliente");
        getContentPane().add(labelIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        labelIdVendedor.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdVendedor.setText("Id vendedor");
        getContentPane().add(labelIdVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelAccesorio.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelAccesorio.setText("Id accesorio");
        getContentPane().add(labelAccesorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        idVendedor.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(idVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 118, -1));

        idMascota.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(idMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 118, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Registro de ventas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        idCliente.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClienteActionPerformed(evt);
            }
        });
        getContentPane().add(idCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 118, -1));

        precio.setEditable(false);
        precio.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioMouseClicked(evt);
            }
        });
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 118, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 80, -1));

        labelIdMascota.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelIdMascota.setText("Id mascota");
        getContentPane().add(labelIdMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        labelPrecio.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelPrecio.setText("Valor total");
        getContentPane().add(labelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        cantidad.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 118, -1));

        labelCantidad.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        labelCantidad.setText("Cantidad");
        getContentPane().add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        botonInstrucciones.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        botonInstrucciones.setText("Instrucciones");
        botonInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botonInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jButton2.setText("Accesorios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton3.setText("Mascotas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Candara", 0, 13)); // NOI18N
        jLabel3.setText("Seleccione el tipo de venta ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 20, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String idVenta = String.valueOf(System.currentTimeMillis());
        switch(opcion.getSelectedItem().toString()){    
            case "Mascota y accesorio":
                ventaControl.almacenarVenta(idVenta, java.time.LocalDateTime.now().toString(), precio.getText().trim(), idCliente.getText().trim(), idVendedor.getText().trim(), idMascota.getText().trim(), idAccesorio.getText().trim(), cantidad.getText().trim());
                break;
            case "Solo mascota": 
                ventaControl.almacenarVenta(idVenta, java.time.LocalDateTime.now().toString(), precio.getText().trim(), idCliente.getText().trim(), idVendedor.getText().trim(), idMascota.getText().trim(), "", "");
                break;
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActionPerformed
        switch(opcion.getSelectedItem().toString()){
            case "Mascota y accesorio":
                activarTodo();                
                break;
            case "Solo mascota":
                activarTodo();
                labelAccesorio.setEnabled(false);
                idAccesorio.setEnabled(false);
                labelCantidad.setEnabled(false);
                cantidad.setEnabled(false);
                break;

        }
    }//GEN-LAST:event_opcionActionPerformed

    private void idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInstruccionesActionPerformed
        Instrucciones instrucciones = new Instrucciones();
        instrucciones.setVisible(true);
    }//GEN-LAST:event_botonInstruccionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AccesorioControlador accesorioListado = new AccesorioControlador();
        accesorioListado.listarAccesorios();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MascotaControlador mascotaListado = new MascotaControlador();
        mascotaListado.listarMascotas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAccesorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAccesorioActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed

    }//GEN-LAST:event_precioActionPerformed

    private void precioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioMouseClicked
        // TODO add your handling code here:
        MascotaDto mascota = mascotaNegocio.consultarMascota(idMascota.getText());
        AccesorioDto accesorio = accesorioNegocio.consultarAccesorio(idAccesorio.getText());
        switch(opcion.getSelectedItem().toString()){
            case "Mascota y accesorio":
                double valorVenta = mascota.getPrecio() + accesorio.getPrecio()*Double.parseDouble(cantidad.getText());
                precio.setText(String.valueOf(valorVenta));
                break;
                
            case "Solo mascota":
                precio.setText(String.valueOf(mascota.getPrecio())); 
                break;
        }
    }//GEN-LAST:event_precioMouseClicked
    
    public void activarTodo(){
        labelIdCliente.setEnabled(true);
        idAccesorio.setEnabled(true);
        labelIdVendedor.setEnabled(true);
        idVendedor.setEnabled(true);
        labelIdMascota.setEnabled(true);
        idMascota.setEnabled(true);
        labelAccesorio.setEnabled(true);
        idAccesorio.setEnabled(true);
        labelCantidad.setEnabled(true);
        cantidad.setEnabled(true);
        labelPrecio.setEnabled(true);
        precio.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonInstrucciones;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField idAccesorio;
    private javax.swing.JTextField idCliente;
    private javax.swing.JTextField idMascota;
    private javax.swing.JTextField idVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelAccesorio;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelIdCliente;
    private javax.swing.JLabel labelIdMascota;
    private javax.swing.JLabel labelIdVendedor;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JComboBox<String> opcion;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables
}
